[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

[licenses]
unlicensed = "deny"
copyleft = "warn"
allow-osi-fsf-free = "either"
default = "deny"
confidence-threshold = 0.8

[licenses.private]
ignore = true

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
deny = [
    { name = "rustls", version = "*" }
]
